### ISSUE TITLE
[BUG] 2.4.5版本发送图片失败

### ISSUE THREAD

**Issue by zdzym** [AHpxChina/Mirai.Net#56]
![屏幕截图(127)](https://user-images.githubusercontent.com/41980497/190683734-a3b5c01d-e026-49ce-85f2-d14c16659efb.png)

相同的一份代码，在2.4.4运行正常，2.4.5则报错如下

![屏幕截图(129)](https://user-images.githubusercontent.com/41980497/190684312-d2414804-04ba-4682-a1e4-b28b192f2cc5.png)

**Comment by Cyl18** [comment]
和 #52 加入了图片高宽有关
