### ISSUE TITLE
缺少BotLeaveEventDisband事件

### ISSUE THREAD

**Issue by bunnyi116** [AHpxChina/Mirai.Net#65]
[Mirai文档](https://docs.mirai.mamoe.net/mirai-api-http/api/EventType.html#bot%E5%9B%A0%E7%BE%A4%E4%B8%BB%E8%A7%A3%E6%95%A3%E7%BE%A4%E8%80%8C%E9%80%80%E5%87%BA%E7%BE%A4-%E6%93%8D%E4%BD%9C%E4%BA%BA%E4%B8%80%E5%AE%9A%E6%98%AF%E7%BE%A4%E4%B8%BB)
```C#
{
  "type": "BotLeaveEventDisband",
  "group": {
    "id": 123456789,
    "name": "Miral Technology",
    "permission": "MEMBER"
  },
  operator: null
}
```
![image](https://user-images.githubusercontent.com/37466008/207986779-074a81b1-2d90-428a-acf1-452ceb79b4a2.png)

**Comment by ksharperd** [comment]
#69 resolve this issue, close
